## Exploratory Data Analysis

This is done to analyze and clean the source csv data before ETL

In [3]:
import pandas as pd
import os

In [4]:
pd.read_csv('../data/raw/source_crm/cust_info.csv')

,cst_id,cst_key,cst_firstname,cst_lastname,cst_marital_status,cst_gndr,cst_create_date
0,11000.0,AW00011000,Jon,Yang,M,M,2025-10-06
1,11001.0,AW00011001,Eugene,Huang,S,M,2025-10-06
2,11002.0,AW00011002,Ruben,Torres,M,M,2025-10-06
3,11003.0,AW00011003,Christy,Zhu,S,F,2025-10-06
4,11004.0,AW00011004,Elizabeth,Johnson,S,F,2025-10-06
...,...,...,...,...,...,...,...
18489,29482.0,AW00029482,Clayton,Zhang,M,NaN,2026-01-25
18490,29483.0,AW00029483,NaN,Navarro,NaN,NaN,2026-01-25
18491,29483.0,AW00029483,Marc,Navarro,M,NaN,2026-01-27
18492,NaN,13451235,NaN,NaN,NaN,NaN,NaN
18493,NaN,A01Ass,NaN,NaN,NaN,NaN,NaN

In [5]:
pd.read_csv('../data/raw/source_crm/prd_info.csv')

,prd_id,prd_key,prd_nm,prd_cost,prd_line,prd_start_dt,prd_end_dt
0,210,CO-RF-FR-R92B-58,HL Road Frame - Black- 58,NaN,R,2003-07-01,NaN
1,211,CO-RF-FR-R92R-58,HL Road Frame - Red- 58,NaN,R,2003-07-01,NaN
2,212,AC-HE-HL-U509-R,Sport-100 Helmet- Red,12.0,S,2011-07-01,2007-12-28
3,213,AC-HE-HL-U509-R,Sport-100 Helmet- Red,14.0,S,2012-07-01,2008-12-27
4,214,AC-HE-HL-U509-R,Sport-100 Helmet- Red,13.0,S,2013-07-01,NaN
...,...,...,...,...,...,...,...
392,602,CO-BB-BB-8107,ML Bottom Bracket,45.0,NaN,2013-07-01,NaN
393,603,CO-BB-BB-9108,HL Bottom Bracket,54.0,NaN,2013-07-01,NaN
394,604,BI-RB-BK-R19B-44,Road-750 Black- 44,344.0,R,2013-07-01,NaN
395,605,BI-RB-BK-R19B-48,Road-750 Black- 48,344.0,R,2013-07-01,NaN
396,606,BI-RB-BK-R19B-52,Road-750 Black- 52,344.0,R,2013-07-01,NaN

In [6]:
pd.read_csv('../data/raw/source_crm/sales_details.csv')

,sls_ord_num,sls_prd_key,sls_cust_id,sls_order_dt,sls_ship_dt,sls_due_dt,sls_sales,sls_quantity,sls_price
0,SO43697,BK-R93R-62,21768,20101229,20110105,20110110,3578.0,1,3578.0
1,SO43698,BK-M82S-44,28389,20101229,20110105,20110110,3400.0,1,3400.0
2,SO43699,BK-M82S-44,25863,20101229,20110105,20110110,3400.0,1,3400.0
3,SO43700,BK-R50B-62,14501,20101229,20110105,20110110,699.0,1,699.0
4,SO43701,BK-M82S-44,11003,20101229,20110105,20110110,3400.0,1,3400.0
...,...,...,...,...,...,...,...,...,...
60393,SO75122,FE-6654,15868,20140128,20140204,20140209,22.0,1,22.0
60394,SO75122,CA-1098,15868,20140128,20140204,20140209,9.0,1,9.0
60395,SO75123,FE-6654,18759,20140128,20140204,20140209,22.0,1,22.0
60396,SO75123,ST-1401,18759,20140128,20140204,20140209,159.0,1,159.0
60397,SO75123,CA-1098,18759,20140128,20140204,20140209,9.0,1,9.0

In [7]:
pd.read_csv('../data/raw/source_erp/CUST_AZ12.csv')

                 CID       BDATE     GEN
0      NASAW00011000  1971-10-06    Male
1      NASAW00011001  1976-05-10    Male
2      NASAW00011002  1971-02-09    Male
3      NASAW00011003  1973-08-14  Female
4      NASAW00011004  1979-08-05  Female
...              ...         ...     ...
18479     AW00029479  1969-06-30     NaN
18480     AW00029480  1977-05-06     NaN
18481     AW00029481  1965-07-04     NaN
18482     AW00029482  1964-09-01     NaN
18483     AW00029483  1965-06-06     NaN

[18484 rows x 3 columns]

In [8]:
pd.read_csv('../data/raw/source_erp/LOC_A101.csv')

               CID           CNTRY
0      AW-00011000       Australia
1      AW-00011001       Australia
2      AW-00011002       Australia
3      AW-00011003       Australia
4      AW-00011004       Australia
...            ...             ...
18479  AW-00029479          France
18480  AW-00029480  United Kingdom
18481  AW-00029481         Germany
18482  AW-00029482          France
18483  AW-00029483          France

[18484 rows x 2 columns]

In [9]:
pd.read_csv('../data/raw/source_erp/PX_CAT_G1V2.csv')

       ID          CAT             SUBCAT MAINTENANCE
0   AC_BR  Accessories         Bike Racks         Yes
1   AC_BS  Accessories        Bike Stands          No
2   AC_BC  Accessories  Bottles and Cages          No
3   AC_CL  Accessories           Cleaners         Yes
4   AC_FE  Accessories            Fenders          No
5   AC_HE  Accessories            Helmets         Yes
6   AC_HP  Accessories    Hydration Packs          No
7   AC_LI  Accessories             Lights         Yes
8   AC_LO  Accessories              Locks         Yes
9   AC_PA  Accessories           Panniers          No
10  AC_PU  Accessories              Pumps         Yes
11  AC_TT  Accessories    Tires and Tubes         Yes
12  BI_MB        Bikes     Mountain Bikes         Yes
13  BI_RB        Bikes         Road Bikes         Yes
14  BI_TB        Bikes      Touring Bikes         Yes
15  CL_BS     Clothing         Bib-Shorts          No
16  CL_CA     Clothing               Caps          No
17  CL_GL     Clothing             Gloves          No
18  CL_JE     Clothing            Jerseys          No
19  CL_SH     Clothing             Shorts          No
20  CL_SO     Clothing              Socks          No
21  CL_TI     Clothing             Tights          No
22  CL_VE     Clothing              Vests          No
23  CO_BB   Components    Bottom Brackets         Yes
24  CO_BR   Components             Brakes         Yes
25  CO_CH   Components             Chains         Yes
26  CO_CS   Components          Cranksets         Yes
27  CO_DE   Components        Derailleurs         Yes
28  CO_FO   Components              Forks         Yes
29  CO_HB   Components         Handlebars          No
30  CO_HS   Components           Headsets          No
31  CO_MF   Components    Mountain Frames         Yes
32  CO_PD   Components             Pedals          No
33  CO_RF   Components        Road Frames         Yes
34  CO_SA   Components            Saddles          No
35  CO_TF   Components     Touring Frames         Yes
36  CO_WH   Components             Wheels         Yes

Removing prefix from varchar columns

In [14]:
location = pd.read_csv('../data/raw/source_erp/LOC_A101.csv')
location['CID'] = location['CID'].str.extract(r'(\d+)$').astype(int)

location.to_csv('../data/processed/erp/locations.csv', index=False)

In [19]:
customers_erp = pd.read_csv('../data/raw/source_erp/CUST_AZ12.csv')
customers_erp['CID'] = customers_erp['CID'].str.extract(r'(\d+)$').astype(int)
customers_erp.to_csv('../data/processed/erp/customers_erp.csv', index=False)

In [60]:
import re
customers_crm = pd.read_csv('../data/raw/source_crm/cust_info.csv')
customers_crm['cst_key'] = customers_crm['cst_key'].apply(
    lambda x: int(re.search(r'\d+$', x).group()) if pd.notnull(x) and re.search(r'\d+$', x) else x
)

customers_crm['cst_id'].dropna(inplace=True)

customers_crm.to_csv('../data/processed/crm/customers_crm.csv', index=False)

In [58]:
customers_crm.to_csv('../data/processed/crm/customers_crm.csv', index=False)

In [40]:
sales_crm = pd.read_csv('../data/raw/source_crm/sales_details.csv')
sales_crm['sls_ord_num'] = sales_crm['sls_ord_num'].str.extract(r'(\d+)$').astype(int)
sales_crm.to_csv('../data/processed/crm/sales_crm.csv', index=False)

In [68]:
import duckdb
import pandas as pd

# Load sample data
customers = pd.read_csv("../data/processed/crm/customers_crm.csv")
locations = pd.read_csv("../data/processed/erp/locations.csv")
birthdates = pd.read_csv("../data/processed/erp/customers_erp.csv")

con = duckdb.connect()
con.register("customers", customers)
con.register("customer_locations", locations)
con.register("customer_birthdates", birthdates)

query = """
 SELECT
            c.cst_id,
            c.first_name,
            c.last_name,
            CASE
                WHEN LOWER(c.gender) = 'f' THEN 'Female'
                WHEN LOWER(c.gender) = 'm' THEN 'Male'
                WHEN LOWER(b.gender) = 'females' THEN 'Female'
                WHEN LOWER(b.gender) = 'males' THEN 'Male'
                ELSE 'Unknown'
            END AS gender,
            c.marital_status,
            l.country,
            b.birthdate AS birth_date,
            c.created_date AS customer_created_date
        FROM customers c
        LEFT JOIN customer_locations l ON c.cst_id = l.cid
        LEFT JOIN customer_birthdates b ON c.cst_id = b.cid;
"""

result = con.execute(query).fetchdf()
print(result.head())

BinderException: Binder Error: Values list "c" does not have a column named "first_name"

LINE 4:             c.first_name,
                    ^