In [16]:
import pandas as pd
import numpy as np

In [18]:
customers = pd.read_csv('../data/customers.csv')
inventory = pd.read_csv('../data/inventory.csv')
products = pd.read_csv('../data/products.csv')
sales = pd.read_csv('../data/sales.csv')
stores = pd.read_csv('../data/stores.csv')
suppliers = pd.read_csv('../data/suppliers.csv')

# Create function to extract data from csv

In [13]:
def extract_from_csv(path):
    return pd.read_csv(path)

Customers

In [19]:
customers = extract_from_csv('../data/raw/customers.csv')

NameError: name 'extract_from_csv' is not defined

In [ ]:
# Clean up needed for phone number column

In [20]:
customers.duplicated().sum()

np.int64(0)

In [21]:
customers.describe()

,customer_id,customer_name,email,phone,address,signup_date
count,10000,10000,10000,10000,10000,10000
unique,10000,9362,9946,10000,10000,2173
top,CUST1000,David Williams,hjohnson@gmail.com,(092)380-5792x59683,"342 Bray Hill, South Christinaview, OR 05031",2020-08-18
freq,1,6,3,1,1,14

In [22]:
customers

,customer_id,customer_name,email,phone,address,signup_date
0,CUST1000,Norma Fisher,robertserin@beasley-thompson.com,(092)380-5792x59683,"342 Bray Hill, South Christinaview, OR 05031",2023-04-27
1,CUST1001,Jorge Sullivan,vlong@villa.net,+1-279-927-3903,"27714 Kelli Club Suite 044, Lake Amy, VT 82999",2023-09-19
2,CUST1002,Elizabeth Woods,hthompson@gmail.com,8125448939,"071 Haas Fields, New Troychester, WY 28053",2019-06-15
3,CUST1003,Susan Wagner,kscott@gmail.com,885.594.5571x38552,"72175 Wendy Isle, Markberg, MI 30956",2021-11-26
4,CUST1004,Peter Montgomery,hollyhernandez@turner-mills.org,001-205-446-8652x663,"5241 Bryce Ways Suite 238, Marshallberg, GA 47746",2024-09-25
...,...,...,...,...,...,...
9995,CUST10995,Dylan Macias,rfaulkner@yahoo.com,024.555.5066x3388,"289 Emily Dam Suite 714, Andersonport, AK 09057",2019-01-11
9996,CUST10996,Margaret Herrera,kevinyoung@hotmail.com,(189)871-2503x2445,"414 Johnson Road Suite 059, Glennmouth, KY 77515",2019-02-04
9997,CUST10997,Mr. Daniel Gould,popepatricia@arellano.com,001-744-070-4029x7985,"99405 John Landing Apt. 671, Kaiserton, WA 30775",2022-04-08
9998,CUST10998,Nathan Mcdonald,rfernandez@yahoo.com,(310)258-3993x780,"0169 Carpenter Lake, North Jason, DE 89695",2024-01-07
9999,CUST10999,David Ramos,galvandavid@jones.com,055.826.8072x22330,"99316 Martin Camp, North Summer, RI 48400",2024-02-09

inventory

In [19]:
inventory.head(10)

  product_id  store_id  stock_level last_updated supplier_id
0   PROD1435  STORE150          474   2024-11-17      SUP165
1   PROD1427  STORE190          410   2023-05-15      SUP244
2   PROD1173  STORE162          472   2024-02-27      SUP237
3   PROD1011  STORE167          322   2024-02-07      SUP296
4   PROD1446  STORE120          345   2025-04-14      SUP218
5   PROD1475  STORE178          422   2023-06-06      SUP238
6   PROD1062  STORE105           31   2024-02-09      SUP252
7   PROD1072  STORE189          238   2024-11-22      SUP142
8   PROD1400  STORE115            5   2024-11-03      SUP185
9   PROD1372  STORE111          360   2023-11-08      SUP145

In [20]:
inventory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    5000 non-null   object
 1   store_id      5000 non-null   object
 2   stock_level   5000 non-null   int64
 3   last_updated  5000 non-null   object
 4   supplier_id   5000 non-null   object
dtypes: int64(1), object(4)
memory usage: 195.4+ KB

In [21]:
inventory.describe()

       stock_level
count  5000.000000
mean    249.436000
std     142.722734
min       0.000000
25%     126.000000
50%     253.000000
75%     373.000000
max     499.000000

In [22]:
inventory.isnull().sum()

product_id      0
store_id        0
stock_level     0
last_updated    0
supplier_id     0
dtype: int64

In [23]:
inventory.duplicated().sum()

np.int64(0)

sales

In [24]:
sales

,sale_id,customer_id,product_id,store_id,sale_date,quantity,total_amount
0,SALE100000,CUST8719,PROD1409,STORE164,2024-11-07,1,377.14
1,SALE100001,CUST1284,PROD1317,STORE178,2025-02-19,2,1467.10
2,SALE100002,CUST1000,PROD1461,STORE159,2025-08-06,9,2517.39
3,SALE100003,CUST5803,PROD1056,STORE177,2025-10-13,1,73.51
4,SALE100004,CUST6851,PROD1115,STORE107,2021-09-01,9,2116.26
...,...,...,...,...,...,...,...
99995,SALE199995,CUST2292,PROD1325,STORE178,2020-12-10,5,698.70
99996,SALE199996,CUST2749,PROD1058,STORE165,2023-10-09,5,2975.35
99997,SALE199997,CUST6201,PROD1026,STORE171,2023-11-26,4,2463.88
99998,SALE199998,CUST7765,PROD1315,STORE148,2021-07-18,2,1113.34
99999,SALE199999,CUST4774,PROD1426,STORE195,2021-04-30,1,502.42

In [30]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   sale_id       100000 non-null  object
 1   customer_id   100000 non-null  object
 2   product_id    100000 non-null  object
 3   store_id      100000 non-null  object
 4   sale_date     100000 non-null  object
 5   quantity      100000 non-null  int64
 6   total_amount  100000 non-null  float64
dtypes: float64(1), int64(1), object(5)
memory usage: 5.3+ MB

In [31]:
sales.describe()

            quantity   total_amount
count  100000.000000  100000.000000
mean        4.988730    2498.231363
std         2.583623    2071.188453
min         1.000000      14.650000
25%         3.000000     812.610000
50%         5.000000    1903.370000
75%         7.000000    3720.000000
max         9.000000    8989.740000

Supplier

In [27]:
suppliers.head(10)

,supplier_id,supplier_name,contact_name,contact_email
0,SUP100,"Johnson, Harris and Edwards",Chad Gray,davidrodriguez@blair-jones.com
1,SUP101,Anderson Ltd,Monique Fowler,sullivanjessica@nguyen.com
2,SUP102,Reynolds-Henry,Chase Baldwin,tlarson@green.com
3,SUP103,Miller Group,Angela Williams,evansmiguel@matthews.biz
4,SUP104,Edwards-Taylor,Kenneth Sutton,deborahramos@hunter-johnson.com
5,SUP105,Arellano PLC,Victor Brown,ricky17@bautista-sanchez.org
6,SUP106,"Moore, Adams and Potter",Pamela Michael,hkaufman@martinez-beard.info
7,SUP107,Lawson-Green,Heidi Walker,crosbyjamie@hoover.biz
8,SUP108,Ramsey Inc,Scott Trevino,castrokatherine@lee.com
9,SUP109,Baldwin Inc,Denise Lewis,richard31@moore-bell.com

In [25]:
suppliers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   supplier_id    200 non-null    object
 1   supplier_name  200 non-null    object
 2   contact_name   200 non-null    object
 3   contact_email  200 non-null    object
dtypes: object(4)
memory usage: 6.4+ KB

In [26]:
suppliers.describe()

,supplier_id,supplier_name,contact_name,contact_email
count,200,200,200,200
unique,200,200,200,200
top,SUP100,"Johnson, Harris and Edwards",Chad Gray,davidrodriguez@blair-jones.com
freq,1,1,1,1

In [28]:
suppliers.isnull().sum()

supplier_id      0
supplier_name    0
contact_name     0
contact_email    0
dtype: int64

In [29]:
suppliers.duplicated().sum()

np.int64(0)

In [41]:
products

    product_id  product_name       category   price
0     PROD1000          High         Snacks  553.33
1     PROD1001      Business      Beverages  718.04
2     PROD1002         Along      Household  606.74
3     PROD1003  Organization  Personal Care  549.43
4     PROD1004          Risk    Electronics  429.42
..         ...           ...            ...     ...
495   PROD1495       Popular    Electronics  278.94
496   PROD1496           Key      Household  460.89
497   PROD1497           Arm         Snacks  407.70
498   PROD1498       Teacher    Electronics  255.93
499   PROD1499        Simply    Electronics  510.81

[500 rows x 4 columns]

In [39]:
import sys
sys.path.append("../src")